# Einführung in Matlab/Octave

Programmieren mit Matlab/Octave in der Jupyter-Umgebung. Im Folgenden nutzen wir die freie Variante Octave, da diese auf der Sagemath-Cloud zur Verfügung steht. Einige Unterschiede zwischen Matlab/Octave und Python werden erwähnt.

 * Kommentare, Magics und Funktionen
 * Hilfefunktionen
 * Variablen, Datentypen
 * Arrays
 * Strings
 * Skripte und Funktionen
 * Bedingungen
 * Schleifen
 
## Kommentare, Magics und Skripte

Sowohl Kommentare als auch die sogenannten Jupyter Magic-Funktion werden mit einem Prozentzeichen eingeleitet. Steht ein Prozentzeichen am Anfang einer Zelle, wird dies als Magic interpretiert. In anderen Zeilen gilt es als Kommentar.

Cell Magics fangen mit zwei %% an und beziehen sich nur auf eine Zelle. Line Magics könnne hingegen Auswirkungen auf die gesamte Jupyter-Umgebung haben.

Mit einem Ausrufezeichen kann man aus den Jupyter-Zellen heraus ein Unix-Kommando oder beliebiges (ausführbares) Skript starten.

In [12]:
%lsmagic

Available line magics:
%activity  %cd  %connect_info  %dot  %download  %edit  %get  %help  %html  %include  %install  %install_magic  %javascript  %jigsaw  %kernel  %kx  %latex  %load  %ls  %lsmagic  %macro  %magic  %parallel  %plot  %pmap  %px  %python  %reload_magics  %restart  %run  %set  %shell

Available cell magics:
%%activity  %%brain  %%debug  %%dot  %%file  %%help  %%html  %%javascript  %%kx  %%latex  %%macro  %%processing  %%px  %%python  %%shell  %%show  %%time  %%tutor


### Cell Magic %%file Dateiname.m

Um Octave-Skripte in Jupyter zu entwickeln, ist das Cell Magic %%file nützlich. Wir brauchen dann keine zusätzliche Datei zu öffnen, sondern haben den Code im Jupyter-Dokument integriert. Um den Code zu ändern, muss die Zelle ausgeführt werden (über Menubutton oder schneller mit Shift+Return).

In [15]:
%%file hallo.m
disp("Hallo!")

Created file '/home/lars/sync/Zeitserien/Zeitreihenanalyse/stunde2/hallo.m'.


In [21]:
!ls -las hallo.m
% Kommentar: Unix Kommando ls

4 -rw-rw-r-- 1 lars lars 14 Apr 13 08:44 hallo.m



In [19]:
!more hallo.m
% Unix Kommando more zeigt den Inhalt einer Textdatei

disp("Hallo!")



In [24]:
hallo
% Starte Octave Skript

Hallo!


## Hilfefunktionen

 * help 
 * lookfor
 * which

In [30]:
which help

'help' is a function from the file /usr/share/octave/3.8.1/m/help/help.m


In [ ]:
!more /usr/share/octave/3.8.1/m/help/help.m

In [29]:
lookfor LinearRegression

LinearRegression    general linear regression


## Variablen, Datentypen

In [1]:
a=2

a =  2


In [2]:
a*2

ans =  4


In [3]:
a

a =  2


In [5]:
a=a*2 % Zuweisung

a =  8


In [6]:
whos

Variables in the current scope:

   Attr Name            Size                     Bytes  Class
   ==== ====            ====                     =====  ===== 
        a               1x1                          8  double
        ans             1x1                          8  double
        figHandles      0x1                          0  double

Total is 2 elements using 16 bytes



In [9]:
clear a 
% Löscht Variable a aus dem Speicher

In [8]:
whos

Variables in the current scope:

   Attr Name            Size                     Bytes  Class
   ==== ====            ====                     =====  ===== 
        ans             1x1                          8  double
        figHandles      0x1                          0  double

Total is 1 element using 8 bytes



In [12]:
c=0+1j
% Komplexe Zahl

c =  0 + 1i


In [13]:
c^2

ans = -1


In [11]:
a=1e9
% Wissenschaftliche Fließkomma-Notation 

a =    1.0000e+09


In [15]:
realmin
% kleinste Fließkommazahl, realmax analog

ans =   2.2251e-308


In [16]:
1/0
% Inf 

ans = Inf


In [17]:
1e309

ans = Inf


In [18]:
eps
# Fließkomma-Rechengenauigkeit

ans =    2.2204e-16


In [19]:
0/0
% Nicht definiert

ans = NaN


In [20]:
a=NaN
b=1
c=a*b

a = NaN
b =  1
c = NaN


In [25]:
format short
% Steuert Ausgabeformat
% Optionen: shorte, longe, hex, blank, +, compact, loose

In [22]:
pi

ans =  3.1416


In [23]:
format long

In [24]:
pi

ans =  3.14159265358979


## Arrays, Schleifen, Initialisierung

In Matlab/Octave können Arrays dynamisch erzeugt werden. Dieses ist in anderen Programmiersprachen aus guten Gründen nicht möglich und erzeugt Fehler. Auch aus Performancegründen ist es sinnvoll, Arrays vor der Nutzung zu Initialisieren. 

Zur Initialisierung stehen folgende Befehle zur Verfügung

 * zeros Füllen mit Nullen
 * ones Füllen mit Einsen
 * eye Identität
 * rand Zufällige Werte (gleichverteilt)
 * randn Zufällige Werte (normalverteilt)

In [29]:
for i=1:3
    x(i)=i
end

x =  1
x =

   1   2

x =

   1   2   3



In [1]:
%pylab
for i in range(3):
    x[i]=i

Using matplotlib backend: Qt4Agg
Populating the interactive namespace from numpy and matplotlib


NameError: name 'x' is not defined

In [2]:
x=zeros(3)
for i in range(3):
    x[i]=i

In [3]:
x

array([ 0.,  1.,  2.])

### Initialisierung und Indizerung

In [1]:
x=[1 2 3]

x =

   1   2   3



In [2]:
x=[1,2,3]
% Kommas oder Leerzeichen sind beide erlaubt. In Python nur Kommas.

x =

   1   2   3



In [3]:
x=[1,2,3;4,5,6;7,8,9]

x =

   1   2   3
   4   5   6
   7   8   9



In [10]:
size(x)

ans =  3


In [12]:
x(3,3)
% Unterschied:
% In Python werden eckige Klammern zur Indizierung verwendet.
% Index startet bei 0, nicht 1 wie in Octave/Matlab

ans =  9


In [13]:
x(2:3,1:3)
% Slicing

ans =

   4   5   6
   7   8   9



In [14]:
ind=x > 4
% Auswahl von Indizes, die Bedingung erfüllen

ind =

   0   0   0
   0   1   1
   1   1   1



In [15]:
x(ind)

ans =

   7
   5
   8
   6
   9



## Bedingungen

In [1]:
a=2;
if a>1
    a=a+1;
end
a

a =  3


In [1]:
a=2
if a>1:
    a=a+1 # Python nutzt Einrückungen als Syntax
a

3